#!/bin/bash

# Script to clean LaTeX auxiliary files

# Dr Jesús Rubio
# jesus@rubiojimenez.com

# Created: February 2024
# Last modified: July 2025

# Extensions to be deleted; add more as needed
delete_files() {
    local extension="$1"
    find . -type f -name "*.$extension" -exec rm -f {} +
}

EXTENSIONS="aux bbl blg end log nav out snm toc" # assumes a pdflatex + bibtex workflow

for ext in $EXTENSIONS; do
    delete_files "$ext"
done

# Auxiliary files to be deleted; add more as needed
file=(*Notes.bib)
[ -f "${file[0]}" ] && rm "${file[0]}"
